import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Navbar from "@/app/nav/Navbar";


export const metadata: Metadata = {
  title: "CarAuct",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
      <Navbar/>
      <main className="container mx-auto px-5 pt-10">
          {children}
      </main>
      </body>
    </html>
  );
}
