apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-svc
  labels:
    app: search-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-svc
  template:
    metadata:
      name: search-svc
      labels:
        app: search-svc
    spec:
      containers:
        - name: search-svc
          image: eimsut/search-svc
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: search-svc-config
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: search-clusterip
spec:
  selector:
    app: search-svc
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
    
      