apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-svc
  labels:
    app: webapp-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-svc
  template:
    metadata:
      name: webapp-svc
      labels:
        app: webapp-svc
    spec:
      containers:
        - name: webapp-svc
          image: sutkaitis/web-app
          imagePullPolicy: Never
          env:
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: authSecret
          envFrom:
            - configMapRef:
                name: webapp-svc-config
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-clusterip
spec:
  selector:
    app: webapp-svc
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
    
      