name: Build and publish

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      continue: 'false'
      
    strategy:
      matrix:
        service:
          - name: 'sutkaitis/auction-svc'
            path: 'src/AuctionService'
          - name: 'sutkaitis/search-svc'
            path: 'src/SearchService'
          - name: 'sutkaitis/bid-svc'
            path: 'src/BiddingService'
          - name: 'sutkaitis/identity-svc'
            path: 'src/IdentityService'
          - name: 'sutkaitis/gateway-svc'
            path: 'src/GatewayService'
          - name: 'sutkaitis/notify-svc'
            path: 'src/NotificationService'
          - name: 'sutkaitis/web-app'
            path: 'frontend'
        
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check for changes
        run: |
          if git diff --quiet HEAD^ HEAD -- ${{matrix.service.path}}; then
            echo "No changes in ${{matrix.service.path}}. Skipping"
            echo "continue=false" >> $GITHUB_ENV
          else
            echo "Changes detected in ${{matrix.service.path}}. Building."
            echo "continue=true" >> $GITHUB_ENV
          fi
          
      - name: Set up Docker buildx
        if: env.continue == 'true'
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker
        if: env.continue == 'true'
        uses: docker/login-action@v3
        with: 
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      
      - name: Build and push docker image
        if: env.continue == 'true'
        uses: docker/build-push-action@v6
        with: 
          context: .
          file: ${{matrix.service.path}}/Dockerfile
          push: true
          tags: ${{matrix.service.name}}:latest
